name: CI

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - main
      - beta

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v22.2.0
      - name: Install commitlint
        run: yarn add commitlint@latest conventional-changelog-conventionalcommits @commitlint/config-conventional
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.6
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.6
      - name: Go Vet
        run: go vet ./...
      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code
      - name: Go Test
        run: go test ./....
